/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppInactiveRouteImport } from './routes/_app.inactive'
import { Route as AppDatabaseRouteImport } from './routes/_app.database'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCopilotRouteImport } from './routes/_app.copilot'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppInactiveRoute = AppInactiveRouteImport.update({
  id: '/inactive',
  path: '/inactive',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabaseRoute = AppDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/copilot': typeof AppCopilotRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/database': typeof AppDatabaseRoute
  '/inactive': typeof AppInactiveRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/copilot': typeof AppCopilotRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/database': typeof AppDatabaseRoute
  '/inactive': typeof AppInactiveRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/database': typeof AppDatabaseRoute
  '/_app/inactive': typeof AppInactiveRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/campaigns'
    | '/copilot'
    | '/customers'
    | '/dashboard'
    | '/database'
    | '/inactive'
    | '/settings'
    | '/upload'
    | '/campaigns/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/campaigns'
    | '/copilot'
    | '/customers'
    | '/dashboard'
    | '/database'
    | '/inactive'
    | '/settings'
    | '/upload'
    | '/campaigns/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/campaigns'
    | '/_app/copilot'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/database'
    | '/_app/inactive'
    | '/_app/settings'
    | '/_app/upload'
    | '/_app/campaigns/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inactive': {
      id: '/_app/inactive'
      path: '/inactive'
      fullPath: '/inactive'
      preLoaderRoute: typeof AppInactiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database': {
      id: '/_app/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AppDatabaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsIdRoute: AppCampaignsIdRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppCopilotRoute: typeof AppCopilotRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatabaseRoute: typeof AppDatabaseRoute
  AppInactiveRoute: typeof AppInactiveRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadRoute: typeof AppUploadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppCopilotRoute: AppCopilotRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatabaseRoute: AppDatabaseRoute,
  AppInactiveRoute: AppInactiveRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadRoute: AppUploadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
